# CMake generated Testfile for 
# Source directory: /work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests
# Build directory: /work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GraphIso.Graph1True "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/graphiso_tests" "--gtest_filter=GraphIso.Graph1True")
set_tests_properties(GraphIso.Graph1True PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;0;")
add_test(GraphIso.Graph2True "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/graphiso_tests" "--gtest_filter=GraphIso.Graph2True")
set_tests_properties(GraphIso.Graph2True PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;0;")
add_test(GraphIso.Graph3False "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/graphiso_tests" "--gtest_filter=GraphIso.Graph3False")
set_tests_properties(GraphIso.Graph3False PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;0;")
add_test(GraphIso.Graph4aTrue "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/graphiso_tests" "--gtest_filter=GraphIso.Graph4aTrue")
set_tests_properties(GraphIso.Graph4aTrue PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;0;")
add_test(GraphIso.Graph4bFalse "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/graphiso_tests" "--gtest_filter=GraphIso.Graph4bFalse")
set_tests_properties(GraphIso.Graph4bFalse PROPERTIES  TIMEOUT "90" WITH_VALGRIND "0" _BACKTRACE_TRIPLES "/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw6/hw6_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw6/hw6_stu_tests/graphiso_tests/CMakeLists.txt;0;")
