# CMake generated Testfile for 
# Source directory: /work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests
# Build directory: /work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Wordle.Empty "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.Empty")
set_tests_properties(Wordle.Empty PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.NoSolutions "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.NoSolutions")
set_tests_properties(Wordle.NoSolutions PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.OneLetterUnconstrained "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.OneLetterUnconstrained")
set_tests_properties(Wordle.OneLetterUnconstrained PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.OneLetterConstrained "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.OneLetterConstrained")
set_tests_properties(Wordle.OneLetterConstrained PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.TwoLetterUnconstrained "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.TwoLetterUnconstrained")
set_tests_properties(Wordle.TwoLetterUnconstrained PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.TwoLetterConstrained "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.TwoLetterConstrained")
set_tests_properties(Wordle.TwoLetterConstrained PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.ThreeLetterFull "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.ThreeLetterFull")
set_tests_properties(Wordle.ThreeLetterFull PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.OneOption "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.OneOption")
set_tests_properties(Wordle.OneOption PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.Nominal1 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.Nominal1")
set_tests_properties(Wordle.Nominal1 PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.Nominal2 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.Nominal2")
set_tests_properties(Wordle.Nominal2 PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.Nominal3 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.Nominal3")
set_tests_properties(Wordle.Nominal3 PROPERTIES  _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
add_test(Wordle.Long "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--trace-children=no" "/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/wordle_tests" "--gtest_filter=Wordle.Long")
set_tests_properties(Wordle.Long PROPERTIES  TIMEOUT "100" _BACKTRACE_TRIPLES "/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/CustomTests.cmake;43;add_test;/work/hw-alamgir/hw5/hw5_stu_tests/test_cmake_lib/TestTargets.cmake;123;add_executable_gtests;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;3;add_source_problem;/work/hw-alamgir/hw5/hw5_stu_tests/wordle_tests/CMakeLists.txt;0;")
